### ISSUE TITLE
Windows binary won't run.

### ISSUE THREAD

**Issue by e5frog** [JeffAlyanak/pcm2pwm#4]
Previous version was running fine on Windows XP (in cmd window or via .bat file).

Version 1.0 won't, it says "not valid Win32 program". Is it perhaps 64bit only?

**Comment by JeffAlyanak** [comment]
Yeah, I think I did compile it as a 64-bit binary this time. Had no idea that anyone was running it in a 32-bit environment.

It will compile just fine in a 32-bit environment, though.

**Comment by e5frog** [comment]
No "biggie", I use a Windows XP machine for most of my programming (32 bit), a lot quicker to use than some other newer machines in this household. 
It's not a program that really requires 64-bits, and 64-bit Windows do run 32-bit applications? So if it was compiled and offered in bin as 32-bit, nobody would have a problem, right?   ;-)
Was just surprised that it wasn't working when the previous version did.

**Comment by JeffAlyanak** [comment]
> No "biggie", I use a Windows XP machine for most of my programming (32 bit), a lot quicker to use than some other newer machines in this household.
> It's not a program that really requires 64-bits, and 64-bit Windows do run 32-bit applications? So if it was compiled and offered in bin as 32-bit, nobody would have a problem, right? ;-)
> Was just surprised that it wasn't working when the previous version did.

Yeah, I wouldn't have changed it consciously since the 32-bit version has the widest compatibility, but my development environment has changed since previous versions and the windows cross-compiler is now a 64-bit one.

I'll add a win32 binary to the release page when I have a change to compile one.

**Comment by JeffAlyanak** [comment]
A 32-bit binary has been added to the releases page: https://github.com/JeffAlyanak/pcm2pwm/releases/tag/v1.0
