### ISSUE TITLE
export to 1bit wav

### ISSUE THREAD

**Issue by T0biasCZe** [JeffAlyanak/pcm2pwm#7]
would it be possible to add option to export the 1bit audio to wave instead of the binary? 
so it could be used with other apps that want 1bit wav?

**Comment by JeffAlyanak** [comment]
I can certainly take a look. Would you be able to provide any example files of 1bit waves in the required format?

@T0biasCZe I don't think I've previously worked with wave files below 8 bits and my reference document on the riff/wave format doesn't specify any bit-depth lower than 8.

**Comment by JeffAlyanak** [comment]
@T0biasCZe Also, if you can provide any examples of software that utilize these 1-bit wave files that would be something I need for testing.

**Comment by JeffAlyanak** [comment]
Closing this for now as I don't have any example files to work from or software to test with.
